add debian 7.3

diff --git a/php-fpm-gost/docker-php-ext-enable b/php-fpm-gost/docker-php-ext-enable
--- a/php-fpm-gost/docker-php-ext-enable
+++ b/php-fpm-gost/docker-php-ext-enable
@@ -1,7 +1,8 @@
 #!/bin/sh
 set -e
 
-cd "$(php -r 'echo ini_get("extension_dir");')"
+extDir="$(php -d 'display_errors=stderr' -r 'echo ini_get("extension_dir");')"
+cd "$extDir"
 
 usage() {
 	echo "usage: $0 [options] module-name [module-name ...]"
@@ -10,7 +11,12 @@ usage() {
 	echo "       $0 --ini-name 0-apc.ini apcu apc"
 	echo
 	echo 'Possible values for module-name:'
-	echo $(find -maxdepth 1 -type f -name '*.so' -exec basename '{}' ';' | sort)
+	find -maxdepth 1 \
+			-type f \
+			-name '*.so' \
+			-exec basename '{}' ';' \
+		| sort \
+		| xargs
 	echo
 	echo 'Some of the above modules are already compiled into PHP; please check'
 	echo 'the output of "php -i" to see which modules are already loaded.'
@@ -47,7 +53,7 @@ for module; do
 		module="$module.so"
 	fi
 	if ! [ -f "$module" ]; then
-		echo >&2 "error: $(readlink -f "$module") does not exist"
+		echo >&2 "error: '$module' does not exist"
 		echo >&2
 		usage >&2
 		exit 1
@@ -80,14 +86,15 @@ fi
 for module in $modules; do
 	if readelf --wide --syms "$module" | grep -q ' zend_extension_entry$'; then
 		# https://wiki.php.net/internals/extensions#loading_zend_extensions
-		line="zend_extension=$(readlink -f "$module")"
+		absModule="$(readlink -f "$module")"
+		line="zend_extension=$absModule"
 	else
 		line="extension=$module"
 	fi
 
 	ext="$(basename "$module")"
 	ext="${ext%.*}"
-	if php -r 'exit(extension_loaded("'"$ext"'") ? 0 : 1);'; then
+	if php -d 'display_errors=stderr' -r 'exit(extension_loaded("'"$ext"'") ? 0 : 1);'; then
 		# this isn't perfect, but it's better than nothing
 		# (for example, 'opcache.so' presents inside PHP as 'Zend OPcache', not 'opcache')
 		echo >&2
@@ -96,12 +103,12 @@ for module in $modules; do
 		continue
 	fi
 
-	ini="/usr/local/etc/php/conf.d/${iniName:-"docker-php-ext-$ext.ini"}"
+	ini="$PHP_INI_DIR/conf.d/${iniName:-"docker-php-ext-$ext.ini"}"
 	if ! grep -q "$line" "$ini" 2>/dev/null; then
 		echo "$line" >> "$ini"
 	fi
 done
 
 if [ "$pm" = 'apk' ] && [ -n "$apkDel" ]; then
-	apk del $apkDel
+	apk del --no-network $apkDel
 fi
